# Generated by Django 2.1.5 on 2019-04-27 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='邮箱')),
                ('name', models.CharField(max_length=64, verbose_name='账户名')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='日志名')),
                ('content', models.TextField(verbose_name='日志内容')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='主机名')),
                ('ip_addr', models.GenericIPAddressField(unique=True, verbose_name='主机地址')),
                ('port', models.SmallIntegerField(default=22, verbose_name='端口')),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='主机分组名')),
            ],
        ),
        migrations.CreateModel(
            name='HostToRemoteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Host', verbose_name='主机名')),
            ],
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='机房名')),
                ('addr', models.CharField(blank=True, max_length=128, null=True, verbose_name='机房地址')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.SmallIntegerField(choices=[(0, 'ssh-password'), (1, 'ssh-key')], default=0, verbose_name='登录主机方式')),
                ('username', models.CharField(max_length=32, verbose_name='主机账户')),
                ('password', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机密码')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='remoteuser',
            unique_together={('auth_type', 'username', 'password')},
        ),
        migrations.AddField(
            model_name='hosttoremoteuser',
            name='remote_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.RemoteUser', verbose_name='主机账户'),
        ),
        migrations.AddField(
            model_name='hostgroup',
            name='host_to_remote_user',
            field=models.ManyToManyField(to='web.HostToRemoteUser', verbose_name='远程主机账户'),
        ),
        migrations.AddField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.IDC', verbose_name='所属机房'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='host_groups',
            field=models.ManyToManyField(blank=True, null=True, to='web.HostGroup', verbose_name='主机组'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='host_to_remote_users',
            field=models.ManyToManyField(blank=True, null=True, to='web.HostToRemoteUser', verbose_name='远程主机账户'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='hosttoremoteuser',
            unique_together={('host', 'remote_user')},
        ),
    ]
