# Generated by Django 2.1.5 on 2019-04-27 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190427_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='name',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='日志记录时间'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='host_to_remote_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.HostToRemoteUser', verbose_name='远程主机'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='log_type',
            field=models.SmallIntegerField(choices=[(0, 'login'), (1, 'cmd'), (2, 'logout')], default=0, verbose_name='日志类型'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='堡垒机账户'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='日志内容'),
        ),
    ]
