# Generated by Django 2.1.7 on 2019-05-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_task_taskdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('cmd', '批量命令'), ('file_transfer', '批量文件')], max_length=64, verbose_name='批量任务类型'),
        ),
    ]
